# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ca6c748d8fa6fc40858cc45de137895679979c6e1dffc0ccf669dc446522d9032f613db0b60ab59b77ca5c7eeed303251572f8aedde8ec1c2f4b45b01d35c0c

test:
  secret_key_base: ff6e310f7a37d9fc0b53e02ab517e7fce2ce2080dce49ba9dfdae8cf5502177cef8eb9d054233f6adbf93b31f6f353c6f0fc263d53e31a15f5912598966af637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
